In [263]:
import pandas as pd
from pathlib import Path
import numpy as np

pd.set_option('display.max_columns', None)

In [264]:
path = Path("../data/despesas_26.csv")

df = pd.read_csv(path)

In [265]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14606 entries, 0 to 14605
Data columns (total 39 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   ano                                       14606 non-null  int64
 1   mes                                       14606 non-null  str
 2   unidade orcamentaria                      14599 non-null  str
 3   categoria                                 14599 non-null  str
 4   ug                                        14606 non-null  int64
 5   nome ug                                   14606 non-null  str
 6   funcao                                    14606 non-null  int64
 7   nome da funcao                            14606 non-null  str
 8   subfuncao                                 14606 non-null  int64
 9   nome da subfuncao                         14606 non-null  str
 10  programa                                  14606 non-null  int64
 11  nome do programa                          14606 non-null  str
 12  programa trabalho                         14606 non-null  int64
 13  projeto ou atividade                      14606 non-null  str
 14  categoria economica                       14606 non-null  int64
 15  nome categoria economica                  14606 non-null  str
 16  grupo de natureza de despesa              14606 non-null  int64
 17  nome grupo de natureza de despesa         14606 non-null  str
 18  modalidade de aplicacao                   14606 non-null  int64
 19  nome modalidade de aplicacao              14223 non-null  str
 20  elemento de despesa orcamentaria          14606 non-null  int64
 21  nome elemento de despesa orcamentaria     12268 non-null  str
 22  natureza de despesa com subelemento       14606 non-null  int64
 23  nome natureza de despesa com subelemento  14606 non-null  str
 24  fonte                                     14606 non-null  int64
 25  nome da fonte                             14599 non-null  str
 26  nº do empenho                             14606 non-null  str
 27  data do empenho                           14606 non-null  str
 28  data da liquidacao                        13663 non-null  str
 29  cpf/cnpj                                  14606 non-null  str
 30  nome do credor                            14606 non-null  str
 31  licitacao                                 14606 non-null  str
 32  referencia legal                          9669 non-null   str
 33  modalidade                                14606 non-null  str
 34  processo                                  14606 non-null  int64
 35  empenhado                                 14606 non-null  float64
 36  liquidado                                 14606 non-null  float64
 37  pago                                      14606 non-null  str
 38  historico                                 14606 non-null  str
dtypes: float64(2), int64(13), str(24)
memory usage: 4.3 MB

In [266]:
df.head(1)

,ano,mes,unidade orcamentaria,categoria,ug,nome ug,funcao,nome da funcao,subfuncao,nome da subfuncao,programa,nome do programa,programa trabalho,projeto ou atividade,categoria economica,nome categoria economica,grupo de natureza de despesa,nome grupo de natureza de despesa,modalidade de aplicacao,nome modalidade de aplicacao,elemento de despesa orcamentaria,nome elemento de despesa orcamentaria,natureza de despesa com subelemento,nome natureza de despesa com subelemento,fonte,nome da fonte,nº do empenho,data do empenho,data da liquidacao,cpf/cnpj,nome do credor,licitacao,referencia legal,modalidade,processo,empenhado,liquidado,pago,historico
0,2026,Janeiro,SECRETARIA DE GOVERNO,Administração Direta,11100,SECRETARIA DO GOVERNO,4,ADMINISTRACAO,122,ADMINISTRACAO GERAL,7,GESTAO INSTITUCIONAL,4122000722320000,PUBLICACAO DE ATOS OFICIAIS DO MUNICCIPIO,30000000,DESPESAS CORRENTES,33000000,OUTRAS DESPESAS CORRENTES,33900000,APLICACOES DIRETAS,33903900,OUTROS SERVICOS DE TERCEIROS-PESSOA JURIDICA,33903933,SERVICOS DE COMUNICACAO EM GERAL,1500000000,RECURSOS NAO VINCULADOS DE IMPOSTOS,2026NE00001,1/12/26,1/30/26,05475103000121,SECRETARIA DE ESTADO DE GOVERNO,CONCURSO,LEI,ESTIMATIVA,13909,1600.0,354.36,0.00,TRATA-SE DE DESPESA REF APRESTACAO DE SERVICO ...

In [267]:
colunas_drop= ['ug','funcao','subfuncao','programa', 'programa trabalho', 'categoria economica', 'grupo de natureza de despesa', 'modalidade de aplicacao', 'elemento de despesa orcamentaria','natureza de despesa com subelemento', 'fonte']

df.drop(columns=colunas_drop, inplace=True)

In [268]:
df.head(1)

,ano,mes,unidade orcamentaria,categoria,nome ug,nome da funcao,nome da subfuncao,nome do programa,projeto ou atividade,nome categoria economica,nome grupo de natureza de despesa,nome modalidade de aplicacao,nome elemento de despesa orcamentaria,nome natureza de despesa com subelemento,nome da fonte,nº do empenho,data do empenho,data da liquidacao,cpf/cnpj,nome do credor,licitacao,referencia legal,modalidade,processo,empenhado,liquidado,pago,historico
0,2026,Janeiro,SECRETARIA DE GOVERNO,Administração Direta,SECRETARIA DO GOVERNO,ADMINISTRACAO,ADMINISTRACAO GERAL,GESTAO INSTITUCIONAL,PUBLICACAO DE ATOS OFICIAIS DO MUNICCIPIO,DESPESAS CORRENTES,OUTRAS DESPESAS CORRENTES,APLICACOES DIRETAS,OUTROS SERVICOS DE TERCEIROS-PESSOA JURIDICA,SERVICOS DE COMUNICACAO EM GERAL,RECURSOS NAO VINCULADOS DE IMPOSTOS,2026NE00001,1/12/26,1/30/26,05475103000121,SECRETARIA DE ESTADO DE GOVERNO,CONCURSO,LEI,ESTIMATIVA,13909,1600.0,354.36,0.00,TRATA-SE DE DESPESA REF APRESTACAO DE SERVICO ...

In [269]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14606 entries, 0 to 14605
Data columns (total 28 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   ano                                       14606 non-null  int64
 1   mes                                       14606 non-null  str
 2   unidade orcamentaria                      14599 non-null  str
 3   categoria                                 14599 non-null  str
 4   nome ug                                   14606 non-null  str
 5   nome da funcao                            14606 non-null  str
 6   nome da subfuncao                         14606 non-null  str
 7   nome do programa                          14606 non-null  str
 8   projeto ou atividade                      14606 non-null  str
 9   nome categoria economica                  14606 non-null  str
 10  nome grupo de natureza de despesa         14606 non-null  str
 11  nome modalidade de aplicacao              14223 non-null  str
 12  nome elemento de despesa orcamentaria     12268 non-null  str
 13  nome natureza de despesa com subelemento  14606 non-null  str
 14  nome da fonte                             14599 non-null  str
 15  nº do empenho                             14606 non-null  str
 16  data do empenho                           14606 non-null  str
 17  data da liquidacao                        13663 non-null  str
 18  cpf/cnpj                                  14606 non-null  str
 19  nome do credor                            14606 non-null  str
 20  licitacao                                 14606 non-null  str
 21  referencia legal                          9669 non-null   str
 22  modalidade                                14606 non-null  str
 23  processo                                  14606 non-null  int64
 24  empenhado                                 14606 non-null  float64
 25  liquidado                                 14606 non-null  float64
 26  pago                                      14606 non-null  str
 27  historico                                 14606 non-null  str
dtypes: float64(2), int64(2), str(24)
memory usage: 3.1 MB

In [270]:
numeric_cols = ['empenhado','liquidado','pago'] # mapeando variações comuns
actual_numeric_cols = [col for col in numeric_cols if col in df.columns]

for col in actual_numeric_cols:
    if df[col].dtype == 'str':
        # Remove pontos de milhar, substitui vírgula por ponto e converte para float
        df[col] = df[col].astype(str).str.replace('.', '', regex=False).str.replace(',', '.', regex=False)
    df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0.0)

In [271]:
df.head(1)

,ano,mes,unidade orcamentaria,categoria,nome ug,nome da funcao,nome da subfuncao,nome do programa,projeto ou atividade,nome categoria economica,nome grupo de natureza de despesa,nome modalidade de aplicacao,nome elemento de despesa orcamentaria,nome natureza de despesa com subelemento,nome da fonte,nº do empenho,data do empenho,data da liquidacao,cpf/cnpj,nome do credor,licitacao,referencia legal,modalidade,processo,empenhado,liquidado,pago,historico
0,2026,Janeiro,SECRETARIA DE GOVERNO,Administração Direta,SECRETARIA DO GOVERNO,ADMINISTRACAO,ADMINISTRACAO GERAL,GESTAO INSTITUCIONAL,PUBLICACAO DE ATOS OFICIAIS DO MUNICCIPIO,DESPESAS CORRENTES,OUTRAS DESPESAS CORRENTES,APLICACOES DIRETAS,OUTROS SERVICOS DE TERCEIROS-PESSOA JURIDICA,SERVICOS DE COMUNICACAO EM GERAL,RECURSOS NAO VINCULADOS DE IMPOSTOS,2026NE00001,1/12/26,1/30/26,05475103000121,SECRETARIA DE ESTADO DE GOVERNO,CONCURSO,LEI,ESTIMATIVA,13909,1600.0,354.36,0.0,TRATA-SE DE DESPESA REF APRESTACAO DE SERVICO ...

In [272]:
int_columns = ['cpf/cnpj', 'processo']

for col in int_columns:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')
        df[col] = df[col].astype('Int64')

In [273]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14606 entries, 0 to 14605
Data columns (total 28 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   ano                                       14606 non-null  int64
 1   mes                                       14606 non-null  str
 2   unidade orcamentaria                      14599 non-null  str
 3   categoria                                 14599 non-null  str
 4   nome ug                                   14606 non-null  str
 5   nome da funcao                            14606 non-null  str
 6   nome da subfuncao                         14606 non-null  str
 7   nome do programa                          14606 non-null  str
 8   projeto ou atividade                      14606 non-null  str
 9   nome categoria economica                  14606 non-null  str
 10  nome grupo de natureza de despesa         14606 non-null  str
 11  nome modalidade de aplicacao              14223 non-null  str
 12  nome elemento de despesa orcamentaria     12268 non-null  str
 13  nome natureza de despesa com subelemento  14606 non-null  str
 14  nome da fonte                             14599 non-null  str
 15  nº do empenho                             14606 non-null  str
 16  data do empenho                           14606 non-null  str
 17  data da liquidacao                        13663 non-null  str
 18  cpf/cnpj                                  10129 non-null  Int64
 19  nome do credor                            14606 non-null  str
 20  licitacao                                 14606 non-null  str
 21  referencia legal                          9669 non-null   str
 22  modalidade                                14606 non-null  str
 23  processo                                  14606 non-null  Int64
 24  empenhado                                 14606 non-null  float64
 25  liquidado                                 14606 non-null  float64
 26  pago                                      14606 non-null  float64
 27  historico                                 14606 non-null  str
dtypes: Int64(2), float64(3), int64(1), str(22)
memory usage: 3.1 MB

In [274]:
df.isna().sum()

ano                                            0
mes                                            0
unidade orcamentaria                           7
categoria                                      7
nome ug                                        0
nome da funcao                                 0
nome da subfuncao                              0
nome do programa                               0
projeto ou atividade                           0
nome categoria economica                       0
nome grupo de natureza de despesa              0
nome modalidade de aplicacao                 383
nome elemento de despesa orcamentaria       2338
nome natureza de despesa com subelemento       0
nome da fonte                                  7
nº do empenho                                  0
data do empenho                                0
data da liquidacao                           943
cpf/cnpj                                    4477
nome do credor                                 0
licitacao                                      0
referencia legal                            4937
modalidade                                     0
processo                                       0
empenhado                                      0
liquidado                                      0
pago                                           0
historico                                      0
dtype: int64

In [275]:
linhas_drop=['unidade orcamentaria','nome modalidade de aplicacao']
df = df.dropna(subset=linhas_drop)

In [276]:
df.head(1)

,ano,mes,unidade orcamentaria,categoria,nome ug,nome da funcao,nome da subfuncao,nome do programa,projeto ou atividade,nome categoria economica,nome grupo de natureza de despesa,nome modalidade de aplicacao,nome elemento de despesa orcamentaria,nome natureza de despesa com subelemento,nome da fonte,nº do empenho,data do empenho,data da liquidacao,cpf/cnpj,nome do credor,licitacao,referencia legal,modalidade,processo,empenhado,liquidado,pago,historico
0,2026,Janeiro,SECRETARIA DE GOVERNO,Administração Direta,SECRETARIA DO GOVERNO,ADMINISTRACAO,ADMINISTRACAO GERAL,GESTAO INSTITUCIONAL,PUBLICACAO DE ATOS OFICIAIS DO MUNICCIPIO,DESPESAS CORRENTES,OUTRAS DESPESAS CORRENTES,APLICACOES DIRETAS,OUTROS SERVICOS DE TERCEIROS-PESSOA JURIDICA,SERVICOS DE COMUNICACAO EM GERAL,RECURSOS NAO VINCULADOS DE IMPOSTOS,2026NE00001,1/12/26,1/30/26,5475103000121,SECRETARIA DE ESTADO DE GOVERNO,CONCURSO,LEI,ESTIMATIVA,13909,1600.0,354.36,0.0,TRATA-SE DE DESPESA REF APRESTACAO DE SERVICO ...

In [277]:
colunas = ['data do empenho', 'data da liquidacao']
def transforma_para_data_correta(df):
    for col in colunas:
        if col in df.columns:
            # 1. Identifica e limpa os caracteres de ruído conhecidos
            # Passamos regex=False porque estamos buscando o texto exato
            df[col] = df[col].astype(str).str.strip().replace(['-', '#N/A', 'nan', 'NAN'], np.nan)
            
            # 2. Faz a conversão inteligente baseada no comportamento do dado
            df[col] = pd.to_datetime(
                df[col],
                format='%m/%d/%y',   # Analisa corretamente o padrão do arquivo
                errors='coerce'  # O que sobrou de texto inválido vira nulo com segurança
            )

            df[col] = df[col].dt.strftime('%d/%m/%Y').where(df[col].notna(), np.nan)
            
            total_nulos = df[col].isna().sum()
            print(f"Coluna '{col}' tratada. Total final de nulos reais: {total_nulos}")

# Lembre-se de recarregar o DataFrame original do CSV antes de rodar a função!
transforma_para_data_correta(df)

Coluna 'data do empenho' tratada. Total final de nulos reais: 0
Coluna 'data da liquidacao' tratada. Total final de nulos reais: 6119

In [278]:
df.isna().sum()

ano                                            0
mes                                            0
unidade orcamentaria                           0
categoria                                      0
nome ug                                        0
nome da funcao                                 0
nome da subfuncao                              0
nome do programa                               0
projeto ou atividade                           0
nome categoria economica                       0
nome grupo de natureza de despesa              0
nome modalidade de aplicacao                   0
nome elemento de despesa orcamentaria       2278
nome natureza de despesa com subelemento       0
nome da fonte                                  7
nº do empenho                                  0
data do empenho                                0
data da liquidacao                          6119
cpf/cnpj                                    4460
nome do credor                                 0
licitacao                                      0
referencia legal                            4727
modalidade                                     0
processo                                       0
empenhado                                      0
liquidado                                      0
pago                                           0
historico                                      0
dtype: int64

In [279]:
df.info()

<class 'pandas.DataFrame'>
Index: 14216 entries, 0 to 14605
Data columns (total 28 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   ano                                       14216 non-null  int64
 1   mes                                       14216 non-null  str
 2   unidade orcamentaria                      14216 non-null  str
 3   categoria                                 14216 non-null  str
 4   nome ug                                   14216 non-null  str
 5   nome da funcao                            14216 non-null  str
 6   nome da subfuncao                         14216 non-null  str
 7   nome do programa                          14216 non-null  str
 8   projeto ou atividade                      14216 non-null  str
 9   nome categoria economica                  14216 non-null  str
 10  nome grupo de natureza de despesa         14216 non-null  str
 11  nome modalidade de aplicacao              14216 non-null  str
 12  nome elemento de despesa orcamentaria     11938 non-null  str
 13  nome natureza de despesa com subelemento  14216 non-null  str
 14  nome da fonte                             14209 non-null  str
 15  nº do empenho                             14216 non-null  str
 16  data do empenho                           14216 non-null  str
 17  data da liquidacao                        8097 non-null   str
 18  cpf/cnpj                                  9756 non-null   Int64
 19  nome do credor                            14216 non-null  str
 20  licitacao                                 14216 non-null  str
 21  referencia legal                          9489 non-null   str
 22  modalidade                                14216 non-null  str
 23  processo                                  14216 non-null  Int64
 24  empenhado                                 14216 non-null  float64
 25  liquidado                                 14216 non-null  float64
 26  pago                                      14216 non-null  float64
 27  historico                                 14216 non-null  str
dtypes: Int64(2), float64(3), int64(1), str(22)
memory usage: 3.2 MB

In [280]:
df.head()

,ano,mes,unidade orcamentaria,categoria,nome ug,nome da funcao,nome da subfuncao,nome do programa,projeto ou atividade,nome categoria economica,nome grupo de natureza de despesa,nome modalidade de aplicacao,nome elemento de despesa orcamentaria,nome natureza de despesa com subelemento,nome da fonte,nº do empenho,data do empenho,data da liquidacao,cpf/cnpj,nome do credor,licitacao,referencia legal,modalidade,processo,empenhado,liquidado,pago,historico
0,2026,Janeiro,SECRETARIA DE GOVERNO,Administração Direta,SECRETARIA DO GOVERNO,ADMINISTRACAO,ADMINISTRACAO GERAL,GESTAO INSTITUCIONAL,PUBLICACAO DE ATOS OFICIAIS DO MUNICCIPIO,DESPESAS CORRENTES,OUTRAS DESPESAS CORRENTES,APLICACOES DIRETAS,OUTROS SERVICOS DE TERCEIROS-PESSOA JURIDICA,SERVICOS DE COMUNICACAO EM GERAL,RECURSOS NAO VINCULADOS DE IMPOSTOS,2026NE00001,12/01/2026,30/01/2026,5475103000121,SECRETARIA DE ESTADO DE GOVERNO,CONCURSO,LEI,ESTIMATIVA,13909,1600.00,354.36,0.00000,TRATA-SE DE DESPESA REF APRESTACAO DE SERVICO ...
1,2026,Janeiro,SECRETARIA DE GOVERNO,Administração Direta,SECRETARIA DO GOVERNO,ADMINISTRACAO,ADMINISTRACAO GERAL,GESTAO INSTITUCIONAL,PUBLICACAO DE ATOS OFICIAIS DO MUNICCIPIO,DESPESAS CORRENTES,OUTRAS DESPESAS CORRENTES,APLICACOES DIRETAS,OUTROS SERVICOS DE TERCEIROS-PESSOA JURIDICA,SERVICOS DE COMUNICACAO EM GERAL,RECURSOS NAO VINCULADOS DE IMPOSTOS,2026NE00002,12/01/2026,12/01/2026,4196645000100,PR - IMPRENSA NACIONAL,CONCURSO,LEI,ESTIMATIVA,785,3800.00,2218.84,2.21884,TRATA-SE DE DESPESA REFE-RENTE AOS SERVICOS DE...
2,2026,Janeiro,SECRETARIA DE GOVERNO,Administração Direta,SECRETARIA DO GOVERNO,ADMINISTRACAO,ADMINISTRACAO GERAL,GESTAO INSTITUCIONAL,SERVICOS DE POSTAGEM E SIMILARES,DESPESAS CORRENTES,OUTRAS DESPESAS CORRENTES,APLICACOES DIRETAS,DESPESAS DE EXERCICIOS ANTERIORES,OUTROS SERV. DE TERCEIROS PESSOA JURIDICA,RECURSOS NAO VINCULADOS DE IMPOSTOS,2026NE00004,19/01/2026,20/01/2026,34028316001509,EMP. .BRAS. DE CORREIOS E TELEGRAFOS,CONCURSO,LEI,ESTIMATIVA,1126,117134.26,117134.26,117.13426,TRATA-SE DE DESPESA DOEXERCIO ANTERIOR REFEREN...
3,2026,Janeiro,SECRETARIA DE GOVERNO,Administração Direta,SECRETARIA DO GOVERNO,ADMINISTRACAO,ADMINISTRACAO GERAL,GESTAO INSTITUCIONAL,ATIVIDADES ADMINISTRATIVAS,DESPESAS CORRENTES,OUTRAS DESPESAS CORRENTES,APLICACOES DIRETAS,OUTROS SERVICOS DE TERCEIROS-PESSOA JURIDICA,OUTROS SERV. TERCEIROS-PESSOA JURID.-PAG.,RECURSOS NAO VINCULADOS DE IMPOSTOS,2026NE00005,20/01/2026,NaN,11713471620,MARIA EDUARDA JORGE DIAS,SUPR.FUND.,LEI,ESTIMATIVA,809,11441.00,0.00,0.00000,FACE AS DESPESAS DE PRON-TO PAGAMENTO - SRRVIÃ...
4,2026,Janeiro,SECRETARIA DE GOVERNO,Administração Direta,SECRETARIA DO GOVERNO,ADMINISTRACAO,ADMINISTRACAO GERAL,GESTAO INSTITUCIONAL,ATIVIDADES ADMINISTRATIVAS,DESPESAS CORRENTES,OUTRAS DESPESAS CORRENTES,APLICACOES DIRETAS,DIARIAS CIVIL,DIARIAS NO PAIS,RECURSOS NAO VINCULADOS DE IMPOSTOS,2026NE00009,23/01/2026,NaN,5211058119,MAIRES BARBOSA DE SOUSA,SUPR.FUND.,LEI,ORDINARIO,1052,12545.00,0.00,0.00000,TRATA-SE DE DESPESA DEPRONTO PAGAMENTO - DIARI...